apiVersion: v1
kind: Service
metadata:
        name: db # This is because result app is written to connect on hostname db
        labels:
                name: db-service
                app: demo-voting-app
spec:
   ports:
     - port: 5432
       targetPort: 5432
   selector:
           name: postgres-pod
           app: demo-voting-app
