apiVersion: v1
kind: Pod
metadata:
        name: postgres-pod
        labels:
                name: postgres-pod
                app: demo-voting-app
spec:
        containers:
                - name: postgres
                  image: postgres:9.4 # version used by example voting app 
                  ports:
                          - containerPort: 5432

